backend:
  name: github
  repo: nithinnani07/blog-test
  branch: master

media_folder: blog/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: tags }